// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  "dropdown-inner": string;
  dropdownInner: string;
  errormsg: string;
}
declare var cssExports: CssExports;
export = cssExports;
