import { TFunction } from "i18next";
import React from "react";
import { makeObservable } from "mobx";
import { observer } from "mobx-react";
import { withTranslation, WithTranslation } from "react-i18next";

import { DefaultTheme, withTheme } from "styled-components";
import Box from "terriajs/lib/Styled/Box";
import Button from "terriajs/lib/Styled/Button";
import Text from "terriajs/lib/Styled/Text";
import withTerriaRef from "terriajs/lib/ReactViews/HOCs/withTerriaRef";
import MenuPanel from "terriajs/lib/ReactViews/StandardUserInterface/customizable/MenuPanel";
import Spacing from "terriajs/lib/Styled/Spacing";

import { ViewState_Arbm as ViewState } from "../../terriajsOverrides/ViewState_Arbm";
import { fetchFromAPI } from "../utils";

import Styles from "./logout-panel.scss";

type PropTypes = WithTranslation & {
  viewState: ViewState;
  refFromHOC?: React.Ref<HTMLDivElement>;
  theme: DefaultTheme;
  t: TFunction;
};

interface LogoutPanelState {
  isOpen: boolean;
}

const INITIAL_STATE: LogoutPanelState = {
  isOpen: false
};

// ==============================================================================================================

//@ts-ignore
@observer
class LogoutPanel extends React.Component<PropTypes, LogoutPanelState> {
  /**
   * @param {Props} props
   */

  keyListener: (e: any) => void;
  abortController?: AbortController;

  // ---------------------------------------------------------------------------------------------------

  constructor(props: PropTypes) {
    super(props);

    this.keyListener = (e) => {
      if (e.key === "Escape") {
        this.closePanel();
      }
    };

    this.state = { ...INITIAL_STATE };
    makeObservable(this);
  }

  // ---------------------------------------------------------------------------------------------------

  componentDidMount = () => {
    window.addEventListener("keydown", this.keyListener, true);
    this.abortController = new AbortController();
  };

  // ---------------------------------------------------------------------------------------------------

  componentWillUnmount = () => {
    window.removeEventListener("keydown", this.keyListener, true);
    this.abortController?.abort();
    this.abortController = undefined;
  };

  // ---------------------------------------------------------------------------------------------------

  private changeOpenState = (open: boolean) => {
    const wasOpen = this.state.isOpen;
    this.setState({ isOpen: open });
    if (wasOpen && !open) {
      this.abortWhileMounted();
    }
  };

  // ---------------------------------------------------------------------------------------------------

  closePanel = () => {
    this.changeOpenState(false);
  };

  // ---------------------------------------------------------------------------------------------------

  private abortWhileMounted() {
    // Each instnce of AbortController can abort() only once, afterwards
    // each new signal generated by the AbortController has a state of being already aborted.
    // Since aborting is supposed to open when the user closes the LoginPanel, but
    // closing the LoginPanel only closes it, but does not necessarily unmount it,
    // we have to re-create a new AbortController for when the user tries again to log in.
    this.abortController?.abort();
    this.abortController = new AbortController();
  }

  // ---------------------------------------------------------------------------------------------------

  getButtonText(t: TFunction): string {
    const user = this.props.viewState.loginData!.user;
    const username = user ? user.username : null;
    return (username ? username + " | " : "") + t("logoutPanel.btnText");
  }

  // ---------------------------------------------------------------------------------------------------

  render() {
    const { t } = this.props;

    const user = this.props.viewState.loginData!.user;
    if (!user) return null;

    const name = user.first_name ? user.first_name : user.username;

    const dropdownTheme = {
      inner: Styles.dropdownInner,
      icon: "user"
    };

    return (
      //@ts-ignore - not yet ready to tackle tsfying MenuPanel
      <MenuPanel
        theme={dropdownTheme}
        btnRef={this.props.refFromHOC}
        btnTitle={t("logoutPanel.btnTitle")} //
        btnText={this.getButtonText(t)} //
        viewState={this.props.viewState}
        smallScreen={this.props.viewState.useSmallScreenInterface}
      >
        <Box padded column>
          <Spacing bottom={3} />
          <Text bold as="label">
            {t("logoutPanel.areYouSure").replace("$name", name)}
          </Text>
          <Spacing bottom={3} />
          <LogoutButton viewState={this.props.viewState} t={t} />
        </Box>
      </MenuPanel>
    );
  }
}

interface ILogoutButtonProps {
  viewState: ViewState;
  t: TFunction;
}

function LogoutButton({ viewState, t }: ILogoutButtonProps) {
  const handleLogoutClick = async () => {
    const signal = this.abortController?.signal ?? null;
    try {
      const _ = await fetchFromAPI(
        viewState,
        signal,
        "auth/logout/session/",
        {},
        "POST"
      );
    } catch (error) {
      if (error.name && error.name !== "AbortError") {
        console.error(error);
      }
    } finally {
      // This updates the UI to show the user as logged out
      viewState.logout();
    }
  };

  return (
    <Button rounded={true} primary={true} onClick={handleLogoutClick}>
      {t("logoutPanel.btnText")}
    </Button>
  );
}

export const LOGOUT_PANEL_NAME = "MenuBarLogoutButton";
export default withTranslation()(
  withTheme(withTerriaRef(LogoutPanel, LOGOUT_PANEL_NAME))
);
